#!/usr/bin/env python3
"""
path_builder.py - make path_data.h from a measured course description,
as an alternative (or starting point) to TEACH.

Course file, one instruction per line (# = comment):
    straight 9.0          drive 9.0 m straight
    right 90 1.2          turn right 90 deg on a 1.2 m radius
    left 45 2.0           turn left 45 deg on a 2.0 m radius
    stop                  waypoint here (10 s stop)
    finish                finish here (last line)
    noobs                 toggle obstacle detection off/on from here

Frame: start at (0,0), x = the direction the car faces at the start.

  python path_builder.py course.txt                -> path_data.h here + preview
  python path_builder.py course.txt -o ../car_firmware/path_data.h

Note: a measured path depends on a well-calibrated gyro (GS) and
counts-per-metre (C). A TEACH path cancels most of those errors, so
prefer TEACH for the final runs and use this for planning/testing.
"""
import argparse, math

SPACING = 0.25


def build(lines):
    pts = [[0.0, 0.0, 0]]
    x = y = h = 0.0
    flags = 0
    for raw in lines:
        l = raw.split("#")[0].strip().lower()
        if not l:
            continue
        w = l.split()
        if w[0] == "straight":
            L = float(w[1])
            n = max(1, math.ceil(L / SPACING))
            for i in range(1, n + 1):
                pts.append([x + math.cos(h) * L * i / n, y + math.sin(h) * L * i / n, flags])
            x, y = pts[-1][0], pts[-1][1]
        elif w[0] in ("left", "right"):
            ang = math.radians(float(w[1])) * (1 if w[0] == "left" else -1)
            r = float(w[2]) if len(w) > 2 else 1.0
            sgn = 1 if ang > 0 else -1
            cx, cy = x - math.sin(h) * r * sgn, y + math.cos(h) * r * sgn
            a0 = math.atan2(y - cy, x - cx)
            n = max(1, math.ceil(abs(ang) * r / SPACING))
            for i in range(1, n + 1):
                a = a0 + ang * i / n
                pts.append([cx + r * math.cos(a), cy + r * math.sin(a), flags])
            x, y = pts[-1][0], pts[-1][1]
            h += ang
        elif w[0] == "stop":
            pts[-1][2] |= 1
        elif w[0] == "finish":
            pts[-1][2] |= 2
        elif w[0] == "noobs":
            flags ^= 4
        else:
            raise SystemExit(f"unknown instruction: {raw.strip()}")
    return pts


def write_header(pts, fn, src):
    with open(fn, "w") as f:
        f.write(f"// path_data.h - generated by path_builder.py from {src}\n")
        f.write("// flags: 1 = STOP (waypoint), 2 = FINISH, 4 = obstacle detection off\n")
        f.write("#pragma once\nconst PathPt BUILTIN_PATH[] = {\n")
        for p in pts:
            f.write(f"  {{{p[0]:.3f}f, {p[1]:.3f}f, {p[2]}}},\n")
        f.write("};\nconst uint16_t BUILTIN_PATH_N = sizeof(BUILTIN_PATH) / sizeof(BUILTIN_PATH[0]);\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("course")
    ap.add_argument("-o", "--out", default="path_data.h")
    ap.add_argument("--no-plot", action="store_true")
    a = ap.parse_args()
    pts = build(open(a.course).read().splitlines())
    write_header(pts, a.out, a.course)
    L = sum(math.dist(pts[i][:2], pts[i - 1][:2]) for i in range(1, len(pts)))
    print(f"{len(pts)} points, {L:.1f} m -> {a.out}")
    print(f"end point: ({pts[-1][0]:.2f}, {pts[-1][1]:.2f})  - should be ~(0,0) for a closed loop")
    if not a.no_plot:
        import matplotlib.pyplot as plt
        plt.plot([p[0] for p in pts], [p[1] for p in pts], ".-")
        for p in pts:
            if p[2] & 1: plt.plot(p[0], p[1], "o", color="orange", ms=10)
            if p[2] & 2: plt.plot(p[0], p[1], "X", color="red", ms=12)
        plt.plot(0, 0, "ks")
        plt.gca().set_aspect("equal"); plt.grid(alpha=0.3); plt.title(a.course)
        plt.show()


if __name__ == "__main__":
    main()
